### PR TITLE
Add Support for EMI, Create in EMI, Inventory Tabs, and Simple Voice Chat

### PR DESCRIPTION
**Pull request by CodeF53**
These are the mod support textures I made for my fork.

They will require some changes because my fork has no hard exterior outlines.

### CODE REVIEW

**Review by ruvaldak — CHANGES_REQUESTED** [review]
Please add hard outlines where necessary & possible in order to fit in with the rest of AquaHUD. Tabs might suck to work with - you'll have to be creative to work around the overlapping hud elements. Remember that overlapping elements sort of "add" their translucency together, so you can use that behavior to get things to remain the correct translucency by "pre-adjusting" it.

**Comment by CodeF53** [comment]
Sorry, but don't you have the ability to make the changes yourself on pull requests? I don't particularly want to put in the effort of adding back the hard outline that I made my fork specifically to remove. 

None of sodium's ui elements have this hard outline, I don't think AquaHUD should have it either. 

The issue with tabs overlapping has already been solved.
https://github.com/Andrew6rant/InventoryTabs/issues/25

**Comment by ruvaldak** [comment]
> Sorry, but don't you have the ability to make the changes yourself on pull requests? I don't particularly want to put in the effort of adding back the hard outline that I made my fork specifically to remove.
> 
> None of sodium's ui elements have this hard outline, I don't think AquaHUD should have it either.
> 
> The issue with tabs overlapping has already been solved. [Andrew6rant/InventoryTabs#25](https://github.com/Andrew6rant/InventoryTabs/issues/25)

Believe I do. I'll look into it.

If it's not too much to ask, could you please provide some screenshots of your fork in use? I agree with you, in that none of Sodium's UI uses the hard outlines, and I'm willing to make an alternate version of AquaHUD official that lacks them. Possible AquaHUD Flat? Might even be able to set up the ability to use respackopts so that users can switch between the versions with just one pack.

Brainstorming, sorry. I like the idea but I remember struggling to get it to look good without the outlines.

**Comment by CodeF53** [comment]
> could you please provide some screenshots of your fork in use?
I have a fair few in the readme of my fork, I will paste the relevant bits of that section here

image
image
image
image
image
image
image

I am still not happy with this beacon texture, but I think you can tell the direction I am going with it
image

These are also gridless because I like UI's that way.
I would be happy to work with you on an official alternate version of aquaHUD with or without the grid depending on what you want.

**Comment by CodeF53** [comment]
discussing over github is slow because I don't get quick notifications for it.

Would you like to discuss this further over discord to bounce ideas off eachother quicker? CodeF53#0241

**Comment by ruvaldak** [comment]
> discussing over github is slow because I don't get quick notifications for it.
> 
> Would you like to discuss this further over discord to bounce ideas off eachother quicker? CodeF53#0241

I sent you a FR on discord.

**Pull request merged**
